# Generated by Django 2.2.5 on 2020-03-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200113_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='team_name',
            field=models.CharField(max_length=128, null=True, verbose_name='チーム名'),
        ),
    ]
