# Generated by Django 2.2.5 on 2020-04-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workplace_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_message',
            name='WorkPlace',
        ),
        migrations.RemoveField(
            model_name='channel_message',
            name='send_member',
        ),
        migrations.RemoveField(
            model_name='direct_message',
            name='WorkPlace',
        ),
        migrations.RemoveField(
            model_name='direct_message',
            name='from_member',
        ),
        migrations.RemoveField(
            model_name='direct_message',
            name='to_member',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='members',
        ),
        migrations.RemoveField(
            model_name='workplacepersonrelation',
            name='User',
        ),
        migrations.RemoveField(
            model_name='workplacepersonrelation',
            name='workPlace',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Channel_message',
        ),
        migrations.DeleteModel(
            name='direct_message',
        ),
        migrations.DeleteModel(
            name='WorkPlace',
        ),
        migrations.DeleteModel(
            name='WorkPlacePersonRelation',
        ),
    ]
